# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package to npmjs

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the branch
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Publish
        run: npm publish --provenance

      - name: Notify Discord of Release
        uses: SethCohen/github-releases-to-discord@v1.20.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          reduce_headings: true
        continue-on-error: true